export default jest.fn();
export const pluginToken =
  "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzYWt1bGkuaW8iLCJzdWIiOiJzYWt1bGlfcGx1Z2luIiwiYXVkIjoid2l0aC1kZWZhdWx0LWFuZC12YWxpZC10b2tlbiIsImNhdGVnb3J5IjoxfQ.BiI2ZNKKfZyKvfFKsYPZSehlzb3jvXMUhkuimrtPEuSyBlCI6rT9Ym_ZTFgK_Ycf0RxXnAYfIVTDVeusk16nKA";
