name: Continuous Delivery
on:
  push:
    branches: [develop]

env:
  CHROMEDRIVER_FILEPATH: "/usr/local/share/chrome_driver/chromedriver"

jobs:
  unit-test:
    strategy:
      matrix:
        node: [12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - name: Run Typedoc
        run: npx lerna run typedoc
      - name: run unit tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm test -- --ci --bail --forceExit

  integration-e2e-test:
    needs: [unit-test]
    strategy:
      matrix:
        node: [12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies [Linux]
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-calculator build-essential libxt-dev libxtst-dev libpng++-dev libxinerama-dev
      - run: npm ci
      - run: npm run build
      - name: run integration tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run test:it
      - name: Run e2e tests [Linux]
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run test:e2e
          options: "-screen 0, 1920x1080x24"
        env:
          LOG_MODE: "ci"
      - name: save error screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: error-screenshots
          path: |
            ./packages/e2e/e2e-suite-chrome/_logs/_screenshots
            ./packages/e2e/e2e-suite-firefox/_logs/_screenshots

  release-next:
    name: release-next
    needs: [integration-e2e-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          fetch-depth: "0"
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Publish next release
        run: npm run lerna:publish-next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Trigger Docker build
        uses: mvasigh/dispatch-action@1.1.6
        with:
          token: ${{ secrets.SAKULIDEV_TOKEN }}
          repo: sakuli-docker
          owner: sakuli
          event_type: build-latest
