name: cd
on:
  push:
    branches: [develop]

jobs:
  release-next:
    name: release-next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: "0"
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Setup NPM token
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc 2> /dev/null
      - name: Run setup script
        run: "bash setup_${{ runner.os }}.sh"
      - name: Run unit/integration tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: "bash run_${{ runner.os }}.sh"
      - name: Publish next release
        run: npm run lerna:publish-next
      - name: Trigger Docker build
        run: bash ./.build/trigger-image-build.sh
        env:
          SAKULIDEV_TOKEN: ${{ secrets.SAKULIDEV_TOKEN }}
